class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<WorkAnniversaryModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <WorkAnniversaryModel>[];
      json['data'].forEach((v) {
        data!.add(WorkAnniversaryModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class WorkAnniversaryModel {
  int? id;
  String? member;
  String? photo;
  int? anniversaryCount;
  int? daysLeft;
  String? doj;

  WorkAnniversaryModel(
      {this.id,
        this.member,
        this.photo,
        this.anniversaryCount,
        this.daysLeft,
        this.doj});

  WorkAnniversaryModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    member = json['member'];
    photo = json['photo'];
    anniversaryCount = json['anniversary_count'];
    daysLeft = json['days_left'];
    doj = json['doj'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['member'] = member;
    data['photo'] = photo;
    data['anniversary_count'] = anniversaryCount;
    data['days_left'] = daysLeft;
    data['doj'] = doj;
    return data;
  }
}
