import 'dart:io';

class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<AllClientModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <AllClientModel>[];
      json['data'].forEach((v) {
        data!.add(AllClientModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AllClientModel {
  int? id;


  File? uploadPicture;
  String? firstName;
  String? lastName;
  String? role;
  String? company;
  String? email;
  String? phone;
  String? countryCode;
  String? countryIsoCode;
  String? password;
  String? passwordConfirmation;
  String? type;
  String? dob;
  String? doj;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zip;
  String? profile;
  int? status;
  int? internalPurpose;
  int? emailVerificationMailSent;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;
  Assigned? assigned;



  AllClientModel({
    this.id,
    this.firstName,
    this.lastName,
    this.role,
    this.company,
    this.email,
    this.phone,
    this.countryCode,
    this.countryIsoCode,
    this.password,
    this.passwordConfirmation,
    this.type,
    this.dob,
    this.doj,
    this.address,
    this.city,
    this.state,
    this.country,
    this.zip,
    this.profile,
    this.status,
    this.internalPurpose,
    this.emailVerificationMailSent,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
    this.assigned,
  });

  AllClientModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    role = json['role'];
    company = json['company'];
    email = json['email'];
    phone = json['phone'];
    countryCode = json['country_code'];
    countryIsoCode = json['country_iso_code'];
    password = json['password'];
    passwordConfirmation = json['password_confirmation'];
    type = json['type'];
    dob = json['dob'];
    doj = json['doj'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    profile = json['profile'];
    status = json['status'];
    internalPurpose = json['internal_purpose'];
    emailVerificationMailSent = json['email_verification_mail_sent'];
    emailVerifiedAt = json['email_verified_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    assigned = json['assigned'] != null ? Assigned.fromJson(json['assigned']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['role'] = role;
    data['company'] = company;
    data['email'] = email;
    data['phone'] = phone;
    data['country_code'] = countryCode;
    data['country_iso_code'] = countryIsoCode;
    data['password'] = password;
    data['password_confirmation'] = passwordConfirmation;
    data['type'] = type;
    data['dob'] = dob;
    data['doj'] = doj;
    data['address'] = address;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zip'] = zip;
    data['profile'] = null;
    data['status'] = status;
    data['internal_purpose'] = internalPurpose;
    data['email_verification_mail_sent'] = emailVerificationMailSent;
    data['email_verified_at'] = emailVerifiedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (assigned != null) {
      data['assigned'] = assigned!.toJson();
    }
    return data;
  }

  Map<String, dynamic> toApi() {
    final Map<String, dynamic> data = <String, dynamic>{};

    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['role'] = role;
    data['company'] = company;
    data['email'] = email;
    data['phone'] = phone;
    data['country_code'] = countryCode;
    data['country_iso_code'] = countryIsoCode;
    data['password'] = password;
    data['password_confirmation'] = passwordConfirmation;
    data['type'] = type;
    data['dob'] = dob;
    data['doj'] = doj;
    data['address'] = address;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zip'] = zip;

    // Send null for profile always
    data['profile'] = null; // Set profile as null explicitly

    data['status'] = status;
    data['internal_purpose'] = internalPurpose;
    data['email_verification_mail_sent'] = emailVerificationMailSent;
    data['email_verified_at'] = emailVerifiedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;

    if (assigned != null) {
      data['assigned'] = assigned!.toJson();
    }

    return data;
  }


  AllClientModel copyWith({
    int? id,
    String? firstName,
    String? lastName,
    String? role,
    String? company,
    String? email,
    String? phone,
    String? countryCode,
    String? countryIsoCode,
    String? password,
    String? passwordConfirmation,
    String? type,
    String? dob,
    String? doj,
    String? address,
    String? city,
    String? state,
    String? country,
    String? zip,
    String? profile,
    int? status,
    int? internalPurpose,
    int? emailVerificationMailSent,
    String? emailVerifiedAt,
    String? createdAt,
    String? updatedAt,
    Assigned? assigned,
  }) {
    return AllClientModel(
      id: id ?? this.id,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      role: role ?? this.role,
      company: company ?? this.company,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      countryCode: (phone != null && phone.isNotEmpty) ? countryCode : "",
      countryIsoCode: countryIsoCode ?? this.countryIsoCode,
      password: password ?? this.password,
      passwordConfirmation: passwordConfirmation ?? this.passwordConfirmation,
      type: type ?? this.type,
      dob: dob ?? this.dob,
      doj: doj ?? this.doj,
      address: address ?? this.address,
      city: city ?? this.city,
      state: state ?? this.state,
      country: country ?? this.country,
      zip: zip ?? this.zip,
      profile: null, // Always set profile to null
      status: status ?? this.status,
      internalPurpose: internalPurpose ?? this.internalPurpose,
      emailVerificationMailSent: emailVerificationMailSent ?? this.emailVerificationMailSent,
      emailVerifiedAt: emailVerifiedAt ?? this.emailVerifiedAt,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      assigned: assigned ?? this.assigned,
    );
  }

}


class Assigned {
  int? projects;
  int? tasks;

  Assigned({this.projects, this.tasks});

  Assigned.fromJson(Map<String, dynamic> json) {
    projects = json['projects'];
    tasks = json['tasks'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['projects'] = projects;
    data['tasks'] = tasks;
    return data;
  }
}
