class Autogenerated {
  bool? error;
  String? message;
  ProfileModel? data;

  Autogenerated({this.error, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    data = json['data'] != null ? ProfileModel.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProfileModel {
  int? id;
  String? firstName;
  String? lastName;
  String? role;
  int? roleId;
  String? email;
  String? phone;
  String? countryCode;
  String? countryIsoCode;
  String? password;
  String? passwordConfirmation;
  String? type;
  String? dob;
  String? doj;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zip;
  String? profile;
  int? status;
  String? fcmToken;
  String? createdAt;
  String? updatedAt;
  Assigned? assigned;
  bool? isAdminOrLeaveEditor;
  bool? isAdminOrHasAllDataAccess;

  ProfileModel(
      {this.id,
        this.firstName,
        this.lastName,
        this.role,
        this.roleId,
        this.email,
        this.phone,
        this.countryCode,
        this.countryIsoCode,
        this.password,
        this.passwordConfirmation,
        this.type,
        this.dob,
        this.doj,
        this.address,
        this.city,
        this.state,
        this.country,
        this.zip,
        this.profile,
        this.status,
        this.fcmToken,
        this.createdAt,
        this.updatedAt,
        this.assigned,
        this.isAdminOrLeaveEditor,
        this.isAdminOrHasAllDataAccess});

  ProfileModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    role = json['role'];
    roleId = json['role_id'];
    email = json['email'];
    phone = json['phone'] ??"";
    countryCode = json['country_code'];
    countryIsoCode = json['country_iso_code'];
    password = json['password'];
    passwordConfirmation = json['password_confirmation'];
    type = json['type'];
    dob = json['dob'];
    doj = json['doj'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    profile = json['profile'];
    status = json['status'];
    fcmToken = json['fcm_token'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    assigned = json['assigned'] != null
        ? Assigned.fromJson(json['assigned'])
        : null;
    isAdminOrLeaveEditor = json['is_admin_or_leave_editor'];
    isAdminOrHasAllDataAccess = json['is_admin_or_has_all_data_access'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['role'] = role;
    data['role_id'] = roleId;
    data['email'] = email;
    data['phone'] = phone;
    data['country_code'] = countryCode;
    data['country_iso_code'] = countryIsoCode;
    data['password'] = password;
    data['password_confirmation'] = passwordConfirmation;
    data['type'] = type;
    data['dob'] = dob;
    data['doj'] = doj;
    data['address'] = address;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zip'] = zip;
    data['profile'] = profile;
    data['status'] = status;
    data['fcm_token'] = fcmToken;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (assigned != null) {
      data['assigned'] = assigned!.toJson();
    }
    data['is_admin_or_leave_editor'] = isAdminOrLeaveEditor;
    data['is_admin_or_has_all_data_access'] = isAdminOrHasAllDataAccess;
    return data;
  }
}

class Assigned {
  int? projects;
  int? tasks;

  Assigned({this.projects, this.tasks});

  Assigned.fromJson(Map<String, dynamic> json) {
    projects = json['projects'];
    tasks = json['tasks'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['projects'] = projects;
    data['tasks'] = tasks;
    return data;
  }
}
