class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<NotificationModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <NotificationModel>[];
      json['data'].forEach((v) {
        data!.add(NotificationModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NotificationModel {
  int? id;
  String? title;
  List<NotiUsers>? users;
  List<NotiClient>? clients;
  String? type;
  int? typeId;
  String? message;
  String? status;
  String? readAt;
  String? createdAt;
  String? updatedAt;

  NotificationModel(
      {this.id,
        this.title,
        this.users,
        this.clients,
        this.type,
        this.typeId,
        this.message,
        this.status,
        this.readAt,
        this.createdAt,
        this.updatedAt});

  NotificationModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    if (json['users'] != null) {
      users = <NotiUsers>[];
      json['users'].forEach((v) {
        users!.add(NotiUsers.fromJson(v));
      });
    }
    if (json['clients'] != null) {
      clients = <NotiClient>[];
      json['clients'].forEach((v) {
        clients!.add(NotiClient.fromJson(v));
      });
    }
    type = json['type'];
    typeId = json['type_id'];
    message = json['message'];
    status = json['status'];
    readAt = json['read_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    if (users != null) {
      data['users'] = users!.map((v) => v.toJson()).toList();
    }
    if (clients != null) {
      data['clients'] = clients!.map((v) => v.toJson()).toList();
    }
    data['type'] = type;
    data['type_id'] = typeId;
    data['message'] = message;
    data['status'] = status;
    data['read_at'] = readAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class NotiUsers {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  NotiUsers({this.id, this.firstName, this.lastName, this.photo});

  NotiUsers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}
class NotiClient {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  NotiClient({this.id, this.firstName, this.lastName, this.photo});

  NotiClient.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}