class Autogenerated {
  bool? error;
  String? message;
  List<MediaModel>? data;
  int? total;

  Autogenerated({this.error, this.message, this.data, this.total});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    if (json['data'] != null) {
      data = <MediaModel>[];
      json['data'].forEach((v) {
        data!.add(new MediaModel.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class MediaModel {
  int? id;
  String? file;
  String? preview;
  String? fileName;
  String? fileSize;
  String? createdAt;
  String? updatedAt;
  bool? canDelete;

  MediaModel(
      {this.id,
        this.file,
        this.fileName,
        this.preview,
        this.fileSize,
        this.createdAt,
        this.updatedAt,
        this.canDelete});

  MediaModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    file = json['file'];
    fileName = json['file_name'];
    preview = json['preview'];
    fileSize = json['file_size'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['file'] = this.file;
    data['preview'] = this.preview;
    data['file_name'] = this.fileName;
    data['file_size'] = this.fileSize;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['can_delete'] = this.canDelete;
    return data;
  }
}
