class Autogenerated {
  bool? error;
  String? message;
  List<Milestone>? data;
  int? total;

  Autogenerated({this.error, this.message, this.data, this.total});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    if (json['data'] != null) {
      data = <Milestone>[];
      json['data'].forEach((v) {
        data!.add(new Milestone.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class Milestone {
  int? id;
  String? title;
  String? status;
  int? progress;
  String? cost;
  String? startDate;
  String? endDate;
  String? createdBy;
  String? description;
  String? createdAt;
  String? updatedAt;

  Milestone(
      {this.id,
        this.title,
        this.status,
        this.progress,
        this.cost,
        this.startDate,
        this.endDate,
        this.createdBy,
        this.description,
        this.createdAt,
        this.updatedAt});

  Milestone.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    status = json['status'];
    progress = json['progress'];
    cost = json['cost'];
    startDate = json['start_date'];
    endDate = json['end_date'];
    createdBy = json['created_by'];
    description = json['description'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['status'] = this.status;
    data['progress'] = this.progress;
    data['cost'] = this.cost;
    data['start_date'] = this.startDate;
    data['end_date'] = this.endDate;
    data['created_by'] = this.createdBy;
    data['description'] = this.description;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }

}
