class Autogenerated {
  bool? error;
  String? message;
  List<StatusTimelineModel>? data;

  Autogenerated({this.error, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    if (json['data'] != null) {
      data = <StatusTimelineModel>[];
      json['data'].forEach((v) {
        data!.add(new StatusTimelineModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class StatusTimelineModel {
  int? id;
  int? entityId;
  String? entityType;
  String? status;
  String? previousStatus;
  String? timeDiff;
  String? newColor;
  String? oldColor;
  String? changedAt;
  String? changedAtTime;
  String? createdAt;
  String? updatedAt;

  StatusTimelineModel(
      {this.id,
        this.entityId,
        this.entityType,
        this.status,
        this.timeDiff,
        this.previousStatus,
        this.newColor,
        this.oldColor,
        this.changedAt,
        this.changedAtTime,
        this.createdAt,
        this.updatedAt});

  StatusTimelineModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    entityId = json['entity_id'];
    entityType = json['entity_type'];
    status = json['status'];
    timeDiff = json['time_diff'];
    previousStatus = json['previous_status'];
    newColor = json['new_color'];
    oldColor = json['old_color'];
    changedAt = json['changed_at'];
    changedAt = json['changed_at'];
    changedAtTime = json['changed_time'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['entity_id'] = this.entityId;
    data['entity_type'] = this.entityType;
    data['status'] = this.status;
    data['time_diff'] = this.timeDiff;
    data['changed_time'] = this.changedAtTime;
    data['previous_status'] = this.previousStatus;
    data['new_color'] = this.newColor;
    data['old_color'] = this.oldColor;
    data['changed_at'] = this.changedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
