class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<ActivityLog>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <ActivityLog>[];
      json['data'].forEach((v) {
        data!.add(ActivityLog.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ActivityLog {
  int? id;
  int? actorId;
  String? actorName;
  String? actorType;
  int? typeId;
  String? parentTypeId;
  String? type;
  String? parentType;
  String? actorProfile;
  String? typeTitle;
  String? parentTypeTitle;
  String? activity;
  String? message;
  String? createdAt;
  String? updatedAt;

  ActivityLog(
      {this.id,
        this.actorId,
        this.actorName,
        this.actorType,
        this.typeId,
        this.parentTypeId,
        this.type,
        this.actorProfile,
        this.parentType,
        this.typeTitle,
        this.parentTypeTitle,
        this.activity,
        this.message,
        this.createdAt,
        this.updatedAt});

  ActivityLog.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    actorId = json['actor_id'];
    actorName = json['actor_name'];
    actorType = json['actor_type'];
    typeId = json['type_id'];
    actorProfile = json['actor_profile'];
    parentTypeId = json['parent_type_id'];
    type = json['type'];
    parentType = json['parent_type'];
    typeTitle = json['type_title'];
    parentTypeTitle = json['parent_type_title'];
    activity = json['activity'];
    message = json['message'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['actor_id'] = actorId;
    data['actor_name'] = actorName;
    data['actor_type'] = actorType;
    data['type_id'] = typeId;
    data['parent_type_id'] = parentTypeId;
    data['type'] = type;
    data['actor_profile'] = actorProfile;
    data['parent_type'] = parentType;
    data['type_title'] = typeTitle;
    data['parent_type_title'] = parentTypeTitle;
    data['activity'] = activity;
    data['message'] = message;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
