class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<Priorities>? priorities;

  Autogenerated({this.error, this.message, this.total, this.priorities});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['priorities'] != null) {
      priorities = <Priorities>[];
      json['priorities'].forEach((v) {
        priorities!.add(Priorities.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (priorities != null) {
      data['priorities'] = priorities!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Priorities {
  int? id;
  String? title;
  String? color;
  String? createdAt;
  String? updatedAt;

  Priorities({this.id, this.title, this.color, this.createdAt, this.updatedAt});

  Priorities.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    color = json['color'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['color'] = color;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
