class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<Statuses>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <Statuses>[];
      json['data'].forEach((v) {
        data!.add(new Statuses.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Statuses {
  int? id;
  String? title;
  String? color;
  Roles? roles;
  String? createdAt;
  String? updatedAt;

  Statuses(
      {this.id,
        this.title,
        this.color,
        this.roles,
        this.createdAt,
        this.updatedAt});

  Statuses.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    color = json['color'];
    roles = json['roles'] != null ? new Roles.fromJson(json['roles']) : null;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['color'] = this.color;
    if (this.roles != null) {
      data['roles'] = this.roles!.toJson();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Roles {
  List<int>? ids;
  List<String>? names;

  Roles({this.ids, this.names});

  Roles.fromJson(Map<String, dynamic> json) {
    ids = json['ids'].cast<int>();
    names = json['names'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ids'] = this.ids;
    data['names'] = this.names;
    return data;
  }
}
