import 'dart:io';

class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<User>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <User>[];
      json['data'].forEach((v) {
        data!.add(User.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  Autogenerated copyWith({
    bool? error,
    String? message,
    int? total,
    List<User>? data,
  }) {
    return Autogenerated(
      error: error ?? this.error,
      message: message ?? this.message,
      total: total ?? this.total,
      data: data ?? this.data,
    );
  }
}


class User {
  File? uploadPicture;
  int? id;
  String? firstName;
  String? lastName;
  String? role;
  int? roleId;
  String? email;
  String? phone;
  String? countryCode;
  String? password;
  String? passwordConfirmation;
  String? type;
  String? dob;
  String? doj;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zip;
  String? profile;
  int? status;
  String? createdAt;
  String? updatedAt;
  Assigned? assigned;
  int? requireEv;

  User(
      {this.id,
        this.firstName,
        this.lastName,
        this.role,
        this.uploadPicture,
        this.roleId,
        this.email,
        this.phone,
        this.countryCode,
        this.password,
        this.passwordConfirmation,
        this.type,
        this.dob,
        this.doj,
        this.address,
        this.city,
        this.state,
        this.country,
        this.zip,
        this.profile,
        this.status,
        this.createdAt,
        this.updatedAt,
        this.assigned,
        this.requireEv});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    role = json['role'];
    roleId = json['role_id'];
    email = json['email'];
    phone = json['phone'];
    countryCode = json['country_code'];
    password = json['password'];
    passwordConfirmation = json['password_confirmation'];
    type = json['type'];
    dob = json['dob'];
    doj = json['doj'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    profile = json['profile'];
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    assigned = json['assigned'] != null
        ? Assigned.fromJson(json['assigned'])
        : null;
    requireEv = json['require_ev'];
  }

  Map<String, dynamic> toJson() {
    print("ghjnmk,l. $phone");
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['role'] = role;
    data['role_id'] = roleId;
    data['email'] = email;
    data['phone'] = phone;
    data['country_code'] =  countryCode;
    data['password'] = password;
    data['password_confirmation'] = passwordConfirmation;
    data['type'] = type;
    data['dob'] = dob;
    data['doj'] = doj;
    data['address'] = address;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zip'] = zip;
    data['profile'] = profile;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (assigned != null) {
      data['assigned'] = assigned!.toJson();
    }
    data['require_ev'] = requireEv;
    if (profile != null && !profile!.startsWith('http') && !profile!.startsWith('https')) {
      data['profile'] = profile;
    }
 
    return data;
  }

  User copyWith({
    int? id,
    String? firstName,
    String? lastName,
    String? role,
    int? roleId,
    String? email,
    String? phone,
    String? countryCode,
    String? password,
    String? passwordConfirmation,
    String? type,
    String? dob,
    String? doj,
    String? address,
    String? city,
    String? state,
    String? country,
    String? zip,
    String? profile,
    int? status,
    String? createdAt,
    String? updatedAt,
    Assigned? assigned,
    int? requireEv,
  }) {
    print("sjkdfds $phone");
    return User(
        id: id ?? this.id,
        firstName: firstName ?? this.firstName,
        lastName: lastName ?? this.lastName,
        role: role ?? this.role,
        roleId: roleId ?? this.roleId,
        email: email ?? this.email,
        phone: phone ?? this.phone,
        countryCode:  countryCode??this.countryCode,
        password: password ?? this.password,
        passwordConfirmation:
        passwordConfirmation ?? this.passwordConfirmation,
        type: type ?? this.type,
        dob: dob ?? this.dob,
        doj: doj ?? this.doj,
        address: address ?? this.address,
        city: city ?? this.city,
        state: state ?? this.state,
        country: country ?? this.country,
        zip: zip ?? this.zip,
        profile: null,
        status: status ?? this.status,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        assigned: assigned ?? this.assigned,
        requireEv:requireEv ?? this.requireEv
    );
  }
}


class Assigned {
  int? projects;
  int? tasks;

  Assigned({this.projects, this.tasks});

  Assigned.fromJson(Map<String, dynamic> json) {
    projects = json['projects'];
    tasks = json['tasks'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['projects'] = projects;
    data['tasks'] = tasks;
    return data;
  }

  Assigned copyWith({
    int? projects,
    int? tasks,
  }) {
    return Assigned(
      projects: projects ?? this.projects,
      tasks: tasks ?? this.tasks,
    );
  }
}

