class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<BirthdayModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <BirthdayModel>[];
      json['data'].forEach((v) {
        data!.add(BirthdayModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class BirthdayModel {
  int? id;
  String? member;
  String? photo;
  int? birthdayCount;
  int? daysLeft;
  String? dob;

  BirthdayModel(
      {this.id,
        this.member,
        this.photo,
        this.birthdayCount,
        this.daysLeft,
        this.dob});

  BirthdayModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    member = json['member'];
    photo = json['photo'];
    birthdayCount = json['birthday_count'];
    daysLeft = json['days_left'];
    dob = json['dob'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['member'] = member;
    data['photo'] = photo;
    data['birthday_count'] = birthdayCount;
    data['days_left'] = daysLeft;
    data['dob'] = dob;
    return data;
  }
}
