class Autogenerated {
  bool? error;
  String? message;
  int? id;
  String? name;
  List<PermissionsInRole>? permissions;

  Autogenerated({this.error, this.message, this.id, this.name, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    id = json['id'];
    name = json['name'];
    if (json['permissions'] != null) {
      permissions = <PermissionsInRole>[];
      json['permissions'].forEach((v) {
        permissions!.add(new PermissionsInRole.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['id'] = this.id;
    data['name'] = this.name;
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PermissionsInRole {
  String? category;
  List<PermissionsAssigned>? permissionsAssigned;

  PermissionsInRole({this.category, this.permissionsAssigned});

  PermissionsInRole.fromJson(Map<String, dynamic> json) {
    category = json['category'];
    if (json['permissions_assigned'] != null) {
      permissionsAssigned = <PermissionsAssigned>[];
      json['permissions_assigned'].forEach((v) {
        permissionsAssigned!.add(new PermissionsAssigned.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['category'] = this.category;
    if (this.permissionsAssigned != null) {
      data['permissions_assigned'] =
          this.permissionsAssigned!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PermissionsAssigned {
  String? action;
  int? id;
  int? isAssigned;
  bool isSelected;
  final int _initialIsAssigned; // Store the original state

  PermissionsAssigned({
    this.action,
    this.id,
    this.isAssigned,
    this.isSelected = false,
  }) : _initialIsAssigned = isAssigned ?? 0; // Store initial state

  // Factory constructor to create an instance from JSON
  factory PermissionsAssigned.fromJson(Map<String, dynamic> json) {
    return PermissionsAssigned(
      action: json['action'],
      id: json['id'],
      isAssigned: json['isAssigned'],
      isSelected: json['isSelected'] ?? false,
    );
  }

  // Method to convert instance to JSON
  Map<String, dynamic> toJson() {
    return {
      'action': action,
      'id': id,
      'isAssigned': isAssigned,
      'isSelected': isSelected,
    };
  }

  // CopyWith method for immutability
  PermissionsAssigned copyWith({
    String? action,
    int? id,
    int? isAssigned,
    bool? isSelected,
  }) {
    return PermissionsAssigned(
      action: action ?? this.action,
      id: id ?? this.id,
      isAssigned: isAssigned ?? this.isAssigned,
      isSelected: isSelected ?? this.isSelected,
    );
  }

  // Getter to access the original state
  int get originalIsAssigned => _initialIsAssigned;
}



