class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<RoleModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <RoleModel>[];
      json['data'].forEach((v) {
        data!.add(RoleModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class RoleModel {
  int? id;
  String? name;
  List<String>? permissions;
  String? color;
  String? createdAt;
  String? updatedAt;
  bool isSelect;  // New field added to indicate selection

  // Constructor
  RoleModel({
    this.id,
    this.name,
    this.color,
    this.createdAt,
    this.updatedAt,
    this.permissions,
    this.isSelect = false,  // Default value for isSelect is false
  });

  // fromJson factory method
  RoleModel.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        color = json['color'],
        permissions = List<String>.from(json['permissions'] ?? []),
        createdAt = json['created_at'],
        updatedAt = json['updated_at'],
        isSelect = json['isSelect'] ?? false;  // Parse isSelect from JSON

  // toJson method
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['color'] = color;
    data['permissions'] = permissions;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['isSelect'] = isSelect;  // Add isSelect to JSON
    return data;
  }

  // copyWith method
  RoleModel copyWith({
    int? id,
    String? name,
    List<String>? permissions,
    String? color,
    String? createdAt,
    String? updatedAt,
    bool? isSelect,  // Make isSelect optional in copyWith
  }) {
    return RoleModel(
      id: id ?? this.id,
      name: name ?? this.name,
      permissions: permissions ?? this.permissions,
      color: color ?? this.color,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isSelect: isSelect ?? this.isSelect,  // Use the passed value for isSelect or retain the current one
    );
  }
}


