class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<Tasks>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <Tasks>[];
      json['data'].forEach((v) {
        data!.add(Tasks.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tasks {
  int? id;
  int? workspaceId;
  String? title;
  String? status;
  int? statusId;
  String? priority;
  int? priorityId;
  List<TaskUsers>? users;
  List<int>? userId;
  List<TaskClients>? clients;
  String? startDate;
  String? dueDate;
  String? project;
  int? projectId;
  String? description;
  String? note;
  int? favorite;
  int? pinned;
  String? createdAt;
  String? updatedAt;

  Tasks(
      {this.id,
        this.workspaceId,
        this.title,
        this.status,
        this.statusId,
        this.priority,
        this.priorityId,
        this.users,
        this.userId,
        this.clients,
        this.startDate,
        this.dueDate,
        this.project,
        this.favorite,
        this.pinned,
        this.projectId,
        this.description,
        this.note,
        this.createdAt,
        this.updatedAt});

  Tasks.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    workspaceId = json['workspace_id'];
    title = json['title'];
    status = json['status'];
    statusId = json['status_id'];
    favorite = json['favorite'];
    pinned = json['pinned'];
    priority = json['priority'];
    priorityId = json['priority_id'];
    if (json['users'] != null && json['users'] is List) {
      users = <TaskUsers>[];
      for (var v in (json['users'] as List)) {
        if (v is Map<String, dynamic>) {
          users!.add(TaskUsers.fromJson(v));
        }
      }
    }
    userId = json['user_id']?.cast<int>();

    // Ensure json['clients'] is a List before processing
    if (json['clients'] != null && json['clients'] is List) {
      clients = <TaskClients>[];
      for (var v in (json['clients'] as List)) {
        if (v is Map<String, dynamic>) {
          clients!.add(TaskClients.fromJson(v));
        }
      }
    }
    startDate = json['start_date'];
    dueDate = json['due_date'];
    project = json['project'];
    projectId = json['project_id'];
    description = json['description'];
    note = json['note'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['workspace_id'] = workspaceId;
    data['title'] = title;
    data['status'] = status;
    data['status_id'] = statusId;
    data['priority'] = priority;
    data['favorite'] = this.favorite;
    data['pinned'] = this.pinned;

    data['priority_id'] = priorityId;
    if (users != null) {
      data['users'] = users!.map((v) => v.toJson()).toList();
    }
    data['user_id'] = userId;
    if (clients != null) {
      data['clients'] = clients!.map((v) => v.toJson()).toList();
    }
    data['start_date'] = startDate;
    data['due_date'] = dueDate;
    data['project'] = project;
    data['project_id'] = projectId;
    data['description'] = description;
    data['note'] = note;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class TaskUsers {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  TaskUsers({this.id, this.firstName, this.lastName, this.photo});

  TaskUsers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}
class TaskClients {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  TaskClients({this.id, this.firstName, this.lastName, this.photo});

  TaskClients.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}