class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<MeetingModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <MeetingModel>[];
      json['data'].forEach((v) {
        data!.add(MeetingModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MeetingModel {
  int? id;
  int? ongoing;
  String? title;
  String? startDate;
  String? startTime;
  String? endDate;
  String? endTime;
  List<MeetingUsers>? users;
  List<int>? userIds;
  List<MeetingClients>? clients;
  List<int>? clientIds;
  String? status;
  String? joinUrl;
  String? createdAt;
  String? updatedAt;

  MeetingModel(
      {this.id,
        this.ongoing,
        this.title,
        this.startDate,
        this.startTime,
        this.endDate,
        this.endTime,
        this.joinUrl,
        this.users,
        this.userIds,
        this.clients,
        this.clientIds,
        this.status,
        this.createdAt,
        this.updatedAt});

  MeetingModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    ongoing = json['ongoing'];
    title = json['title'];
    startDate = json['start_date'];
    startTime = json['start_time'];
    endDate = json['end_date'];
    endTime = json['end_time'];
    if (json['users'] != null) {
      users = <MeetingUsers>[];
      json['users'].forEach((v) {
        users!.add(MeetingUsers.fromJson(v));
      });
    }
    userIds = json['user_ids'].cast<int>();
    if (json['clients'] != null) {
      clients = <MeetingClients>[];
      json['clients'].forEach((v) {
        clients!.add(MeetingClients.fromJson(v));
      });
    }
    clientIds = json['client_ids'].cast<int>();
    status = json['status'];
    joinUrl = json['join_url'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['ongoing'] = ongoing;
    data['title'] = title;
    data['start_date'] = startDate;
    data['start_time'] = startTime;
    data['end_date'] = endDate;
    data['end_time'] = endTime;
    if (users != null) {
      data['users'] = users!.map((v) => v.toJson()).toList();
    }
    data['user_ids'] = userIds;
    if (clients != null) {
      data['clients'] = clients!.map((v) => v.toJson()).toList();
    }
    data['client_ids'] = clientIds;
    data['status'] = status;
    data['join_url'] = joinUrl;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class MeetingUsers {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  MeetingUsers({this.id, this.firstName, this.lastName, this.photo});

  MeetingUsers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}

class MeetingClients {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  MeetingClients({this.id, this.firstName, this.lastName, this.photo});

  MeetingClients.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}
