
class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<DashBoardLeaveReq>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <DashBoardLeaveReq>[];
      json['data'].forEach((v) {
        data!.add(DashBoardLeaveReq.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class DashBoardLeaveReq {
  int? id;
  String? member;
  String? photo;
  String? fromDate;
  String? toDate;
  String? type;
  String? duration;
  int? daysLeft;

  DashBoardLeaveReq(
      {this.id,
        this.member,
        this.photo,
        this.fromDate,
        this.toDate,
        this.type,
        this.duration,
        this.daysLeft});

  DashBoardLeaveReq.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    member = json['member'];
    photo = json['photo'];
    fromDate = json['from_date'];
    toDate = json['to_date'];
    type = json['type'];
    duration = json['duration'];
    daysLeft = json['days_left'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{}; // Use the map literal syntax
    data['id'] = id; // No need for 'this.'
    data['member'] = member; // No need for 'this.'
    data['photo'] = photo; // No need for 'this.'
    data['from_date'] = fromDate; // No need for 'this.'
    data['to_date'] = toDate; // No need for 'this.'
    data['type'] = type; // No need for 'this.'
    data['duration'] = duration; // No need for 'this.'
    data['days_left'] = daysLeft; // No need for 'this.'
    return data;
  }


}
