class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<LeaveRequests>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <LeaveRequests>[];
      json['data'].forEach((v) {
        data!.add(LeaveRequests.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['error'] = error;
    data['message'] = message;
    data['total'] = total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class LeaveRequests {
  int? id;
  int? userId;
  String? userName;
  String? userPhoto;
  String? actionBy;
  int? actionById;
  String? fromDate;
  String? fromTime;
  String? toDate;
  String? toTime;
  String? type;
  String? leaveVisibleToAll;
  String? partialLeave;
  String? duration;
  String? reason;
  String? status;
  List<VisibleTo>? visibleTo;
  List<int>? visibleToIds;
  String? createdAt;
  String? updatedAt;

  LeaveRequests(
      {this.id,
        this.userId,
        this.userName,
        this.userPhoto,
        this.actionBy,
        this.actionById,
        this.fromDate,
        this.fromTime,
        this.toDate,
        this.toTime,
        this.type,
        this.leaveVisibleToAll,
        this.partialLeave,
        this.duration,
        this.reason,
        this.status,
        this.visibleTo,
        this.visibleToIds,
        this.createdAt,
        this.updatedAt});

  LeaveRequests.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    userName = json['user_name'];
    userPhoto = json['user_photo'];
    actionBy = json['action_by'];
    actionById = json['action_by_id'];
    fromDate = json['from_date'];
    fromTime = json['from_time'];
    toDate = json['to_date'];
    toTime = json['to_time'];
    type = json['type'];
    leaveVisibleToAll = json['leaveVisibleToAll'];
    partialLeave = json['partialLeave'];
    duration = json['duration'];
    reason = json['reason'];
    status = json['status'];
    if (json['visible_to'] != null) {
      visibleTo = <VisibleTo>[];
      json['visible_to'].forEach((v) {
        visibleTo!.add(VisibleTo.fromJson(v));
      });
    }
    visibleToIds = json['visible_to_ids'].cast<int>();
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['user_name'] = userName;
    data['user_photo'] = userPhoto;
    data['action_by'] = actionBy;
    data['action_by_id'] = actionById;
    data['from_date'] = fromDate;
    data['from_time'] = fromTime;
    data['to_date'] = toDate;
    data['to_time'] = toTime;
    data['type'] = type;
    data['leaveVisibleToAll'] = leaveVisibleToAll;
    data['partialLeave'] = partialLeave;
    data['duration'] = duration;
    data['reason'] = reason;
    data['status'] = status;
    if (visibleTo != null) {
      data['visible_to'] = visibleTo!.map((v) => v.toJson()).toList();
    }
    data['visible_to_ids'] = visibleToIds;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class VisibleTo {
  int? id;
  String? firstName;
  String? lastName;
  String? photo;

  VisibleTo({this.id, this.firstName, this.lastName, this.photo});

  VisibleTo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    return data;
  }
}
