

class Autogenerated {
  bool? error;
  String? message;
  Data? data;

  Autogenerated({this.error, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? totalProjects;
  int? totalTasks;
  int? totalUsers;
  int? totalClients;
  int? totalMeetings;
  int? totalTodos;
  int? completedTodos;
  int? pendingTodos;
  List<StatusWiseProjects>? statusWiseProjects;
  List<StatusWiseTasks>? statusWiseTasks;

  Data(
      {this.totalProjects,
        this.totalTasks,
        this.totalUsers,
        this.totalClients,
        this.totalMeetings,
        this.totalTodos,
        this.completedTodos,
        this.pendingTodos,
        this.statusWiseProjects,
        this.statusWiseTasks});

  Data.fromJson(Map<String, dynamic> json) {
    totalProjects = json['total_projects'];
    totalTasks = json['total_tasks'];
    totalUsers = json['total_users'];
    totalClients = json['total_clients'];
    totalMeetings = json['total_meetings'];
    totalTodos = json['total_todos'];
    completedTodos = json['completed_todos'];
    pendingTodos = json['pending_todos'];
    if (json['status_wise_projects'] != null) {
      statusWiseProjects = <StatusWiseProjects>[];
      json['status_wise_projects'].forEach((v) {
        statusWiseProjects!.add(new StatusWiseProjects.fromJson(v));
      });
    }
    if (json['status_wise_tasks'] != null) {
      statusWiseTasks = <StatusWiseTasks>[];
      json['status_wise_tasks'].forEach((v) {
        statusWiseTasks!.add(new StatusWiseTasks.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total_projects'] = this.totalProjects;
    data['total_tasks'] = this.totalTasks;
    data['total_users'] = this.totalUsers;
    data['total_clients'] = this.totalClients;
    data['total_meetings'] = this.totalMeetings;
    data['total_todos'] = this.totalTodos;
    data['completed_todos'] = this.completedTodos;
    data['pending_todos'] = this.pendingTodos;
    if (this.statusWiseProjects != null) {
      data['status_wise_projects'] =
          this.statusWiseProjects!.map((v) => v.toJson()).toList();
    }
    if (this.statusWiseTasks != null) {
      data['status_wise_tasks'] =
          this.statusWiseTasks!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class StatusWiseProjects {
  int? id;
  String? title;
  String? color;
  int? totalProjects;
  String? chartcolor;

  StatusWiseProjects({this.id, this.title, this.color, this.totalProjects,this.chartcolor});

  StatusWiseProjects.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    color = json['color'];
    chartcolor = json['chart_color'];
    totalProjects = json['total_projects'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['color'] = this.color;
    data['chart_color'] = this.chartcolor;
    data['total_projects'] = this.totalProjects;
    return data;
  }
}

class StatusWiseTasks {
  int? id;
  String? title;
  String? color;
  String? chart_color;
  int? totalTasks;

  StatusWiseTasks({this.id, this.title, this.color, this.totalTasks,this.chart_color});

  StatusWiseTasks.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    color = json['color'];
    chart_color = json['chart_color'];
    totalTasks = json['total_tasks'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['color'] = this.color;
    data['chart_color'] = this.chart_color;
    data['total_tasks'] = this.totalTasks;
    return data;
  }
}
